### PR TITLE
CodePen (Fixing the name)

### PR DESCRIPTION
**Pull request by gabriel-brito**
Just fixing codepen name!

Btw: Thanks for translate to pt-br! :smile:

### CODE REVIEW

**Comment by LFeh** [comment]
Can you add this adjust in source too?

Thanks!

**Comment by gabriel-brito** [comment]
Sorry? I don't get it.. I didn't find any other "CodePeb" :o

**Comment by LFeh** [comment]
Here https://github.com/gabriel-brito/lfeh.github.io/blob/master/_harp/public/blog/2016/do-zero-a-heroi-do-front-end-parte-1.md

**Comment by gabriel-brito** [comment]
Now it's done correctly! 

Again: Thanks for this great translation! :smile:

**Comment by LFeh** [comment]
TKS!

**Pull request merged**
